apiVersion: batch/v1
kind: Job
metadata:
  name: aws-image-deletion
  namespace: openshift-sandboxed-containers-operator
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 1
  template:
    metadata:
      name: aws-image-deletion
    spec:
      restartPolicy: Never
      containers:
      - name: aws-image-deletion
        image: registry.access.redhat.com/ubi9/ubi:9.2
        securityContext:
          runAsUser: 0 # needed for container mode dnf access
        envFrom:
        - secretRef:
            name: peer-pods-secret
        - configMapRef:
            name: peer-pods-cm
            optional: true
        env:
          - name: PODVM_DISTRO
            value: rhel
        command:
        - /bin/sh
        - -c
        - |
          set -e
          [[ ! "${PODVM_AMI_ID}" ]] && echo "PODVM_AMI_ID is missing, it's unknown which image to delete" && exit 1
          [[ "${IMAGE_NAME}" ]] && echo "IMAGE_NAME:${IMAGE_NAME} is set, it implies image was not automatically created, delete it manually" && exit 0
          dnf install -y unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          ./aws/install
          PATH="/usr/bin:${PATH}"
          export MAC=$(curl -m 3 -s http://169.254.169.254/latest/meta-data/mac)
          [[ ! "${AWS_REGION}" ]] && export AWS_REGION=$(curl -m 30 -s --show-error http://169.254.169.254/latest/meta-data/placement/region)
          [[ ! "${AWS_REGION}" ]] && echo "AWS_REGION is missing" && exit 1
          echo "Deleting AMI: ${PODVM_AMI_ID}"
          RES=$(aws ec2 deregister-image --image-id "${PODVM_AMI_ID}" --region "${AWS_REGION}" 2>&1) || ERR=true
          echo ${RES}
          [[ ${ERR} ]] && [[ "$RES" =~ InvalidAMIID\.(Unavailable|NotFound) ]] # if deregister returned error and image is already deleted, continue
          echo "Deleted AMI: ${PODVM_AMI_ID} - DONE"
